//Actions
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const ADD_ITEM = 'ADD_ITEM';
export const FETCH_ITEM = 'FETCH_ITEM';
export const SEARCH_ITEM = 'SEARCH_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CREATE_ITEM = 'CREATE_ITEM';
export const FETCH_LIST_ITEMS = 'FETCH_LIST_ITEMS';
export const SUCCESS = 'ALERT_SUCCESS';
export const ERROR = 'ALERT_ERROR';
export const CLEAR = 'ALERT_CLEAR';


//State of pages: loading, loaded, errored;
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_LOADING = 'HOME_PAGE_LOADING';
export const HOME_PAGE_ERRORED = 'HOME_PAGE_ERRORED';

export const ORDER_PAGE_LOADED = 'ORDER_PAGE_LOADED';
export const ORDER_PAGE_LOADING = 'ORDER_PAGE_LOADING';
export const ORDER_PAGE_ERRORED = 'ORDER_PAGE_ERRORED';

export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED';
export const LOGIN_PAGE_LOADING = 'LOGIN_PAGE_LOADING';
export const LOGIN_PAGE_ERRORED = 'LOGIN_PAGE_ERRORED';

export const LIST_ITEMS_PAGE_LOADED = 'LIST_ITEMS_PAGE_LOADED';
export const LIST_ITEMS_PAGE_LOADING = 'LIST_ITEMS_PAGE_LOADING';
export const LIST_ITEMS_PAGE_ERRORED = 'LIST_ITEMS_PAGE_ERRORED';

export const ITEM_DETAIL_PAGE_LOADED = 'ITEM_DETAIL_PAGE_LOADED';
export const ITEM_DETAIL_PAGE_LOADING = 'ITEM_DETAIL_PAGE_LOADING';
export const ITEM_DETAIL_PAGE_ERRORED = 'ITEM_DETAIL_PAGE_ERRORED';

export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED';
export const PROFILE_PAGE_LOADING = 'PROFILE_PAGE_LOADING';
export const PROFILE_PAGE_ERRORED = 'PROFILE_PAGE_ERRORED';
