//Actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const SUCCESS_ALERT = 'SUCCESS_ALERT';
export const ERROR_ALERT = 'ERROR_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

//Product actions
export const  FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const  FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const  FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const  SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST';
export const  SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const  SEARCH_PRODUCT_FAILURE = 'SEARCH_PRODUCT_FAILURE';

export const  DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const  DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const  DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

export const  CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const  CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const  CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const  ADD_PRODUCT_TO_ORDER_REQUEST = 'ADD_PRODUCT_TO_ORDER_REQUEST';
export const  ADD_PRODUCT_TO_ORDER_SUCCESS = 'ADD_PRODUCT_TO_ORDER_SUCCESS';
export const  ADD_PRODUCT_TO_ORDER_FAILURE = 'ADD_PRODUCT_TO_ORDER_FAILURE';

//User actions
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const  DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const  DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const  DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const  SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const  SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const  SEARCH_USER_FAILURE = 'SEARCH_USER_FAILURE';

export const  CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const  CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const  CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';


//Order actions
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const  DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const  DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const  DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';

export const  SEARCH_ORDER_REQUEST = 'SEARCH_ORDER_REQUEST';
export const  SEARCH_ORDER_SUCCESS = 'SEARCH_ORDER_SUCCESS';
export const  SEARCH_ORDER_FAILURE = 'SEARCH_ORDER_FAILURE';

export const  CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const  CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const  CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';





//State of pages: loading, loaded, errored;

export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED';
export const LOGIN_PAGE_LOADING = 'LOGIN_PAGE_LOADING';
export const LOGIN_PAGE_ERRORED = 'LOGIN_PAGE_ERRORED';

export const REGISTER_PAGE_LOADED = 'REGISTER_PAGE_LOADED';
export const REGISTER_PAGE_LOADING = 'REGISTER_PAGE_LOADING';
export const REGISTER_PAGE_ERRORED = 'REGISTER_PAGE_ERRORED';

export const CONTACT_PAGE_LOADED = 'CONTACT_PAGE_LOADED';
export const CONTACT_PAGE_LOADING = 'CONTACT_PAGE_LOADING';
export const CONTACT_PAGE_ERRORED = 'CONTACT_PAGE_ERRORED';

export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_LOADING = 'HOME_PAGE_LOADING';
export const HOME_PAGE_ERRORED = 'HOME_PAGE_ERRORED';

export const LIST_PRODUCTS_PAGE_LOADED = 'LIST_PRODUCTS_PAGE_LOADED';
export const LIST_PRODUCTS_PAGE_LOADING = 'LIST_PRODUCTS_PAGE_LOADING';
export const LIST_PRODUCTS_PAGE_ERRORED = 'LIST_PRODUCTS_PAGE_ERRORED';

export const PRODUCT_DETAIL_PAGE_LOADED = 'PRODUCT_DETAIL_PAGE_LOADED';
export const PRODUCT_DETAIL_PAGE_LOADING = 'PRODUCT_DETAIL_PAGE_LOADING';
export const PRODUCT_DETAIL_PAGE_ERRORED = 'PRODUCT_DETAIL_PAGE_ERRORED';

export const DASHBOARD_PAGE_LOADED = 'DASHBOARD_PAGE_LOADED';
export const DASHBOARD_PAGE_LOADING = 'DASHBOARD_PAGE_LOADING';
export const DASHBOARD_PAGE_ERRORED = 'DASHBOARD_PAGE_ERRORED';

export const ORDER_PAGE_LOADED = 'ORDER_PAGE_LOADED';
export const ORDER_PAGE_LOADING = 'ORDER_PAGE_LOADING';
export const ORDER_PAGE_ERRORED = 'ORDER_PAGE_ERRORED';

export const INVOICE_PAGE_LOADED = 'INVOICE_PAGE_LOADED';
export const INVOICE_PAGE_LOADING = 'INVOICE_PAGE_LOADING';
export const INVOICE_PAGE_ERRORED = 'INVOICE_PAGE_ERRORED';
