//Actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const FETCH_LIST_PRODUCTS = 'FETCH_LIST_PRODUCTS';

export const SUCCESS_ALERT = 'SUCCESS_ALERT';
export const ERROR_ALERT = 'ERROR_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';


//State of pages: loading, loaded, errored;

export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED';
export const LOGIN_PAGE_LOADING = 'LOGIN_PAGE_LOADING';
export const LOGIN_PAGE_ERRORED = 'LOGIN_PAGE_ERRORED';

export const REGISTER_PAGE_LOADED = 'REGISTER_PAGE_LOADED';
export const REGISTER_PAGE_LOADING = 'REGISTER_PAGE_LOADING';
export const REGISTER_PAGE_ERRORED = 'REGISTER_PAGE_ERRORED';

export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_LOADING = 'HOME_PAGE_LOADING';
export const HOME_PAGE_ERRORED = 'HOME_PAGE_ERRORED';

export const LIST_PRODUCTS_PAGE_LOADED = 'LIST_PRODUCTS_PAGE_LOADED';
export const LIST_PRODUCTS_PAGE_LOADING = 'LIST_PRODUCTS_PAGE_LOADING';
export const LIST_PRODUCTS_PAGE_ERRORED = 'LIST_PRODUCTS_PAGE_ERRORED';

export const PRODUCT_DETAIL_PAGE_LOADED = 'PRODUCT_DETAIL_PAGE_LOADED';
export const PRODUCT_DETAIL_PAGE_LOADING = 'PRODUCT_DETAIL_PAGE_LOADING';
export const PRODUCT_DETAIL_PAGE_ERRORED = 'PRODUCT_DETAIL_PAGE_ERRORED';

export const DASHBOARD_PAGE_LOADED = 'DASHBOARD_PAGE_LOADED';
export const DASHBOARD_PAGE_LOADING = 'DASHBOARD_PAGE_LOADING';
export const DASHBOARD_PAGE_ERRORED = 'DASHBOARD_PAGE_ERRORED';

export const ORDER_PAGE_LOADED = 'ORDER_PAGE_LOADED';
export const ORDER_PAGE_LOADING = 'ORDER_PAGE_LOADING';
export const ORDER_PAGE_ERRORED = 'ORDER_PAGE_ERRORED';

export const INVOICE_PAGE_LOADED = 'INVOICE_PAGE_LOADED';
export const INVOICE_PAGE_LOADING = 'INVOICE_PAGE_LOADING';
export const INVOICE_PAGE_ERRORED = 'INVOICE_PAGE_ERRORED';
